/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/sample-island.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Icosphere008.geometry} material={nodes.Icosphere008.material} position={[-0.26, -0.02, 3.27]} rotation={[0.29, -0.94, 0.15]} scale={0.26} />
      <mesh geometry={nodes.Cylinder017.geometry} material={nodes.Cylinder017.material} position={[-0.54, 0.03, -3.08]} rotation={[0, -0.64, 0]} scale={0.06} />
      <mesh geometry={nodes.Icosphere001.geometry} material={materials['Ground&Mountain Texture']} scale={1.4} />
      <mesh geometry={nodes.Icosphere015.geometry} material={nodes.Icosphere015.material} position={[-2.33, -0.08, 1.33]} rotation={[0.04, -0.96, 0.03]} scale={0.06} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} />
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[0, 1.91, 0]} rotation={[0.44, 0, -Math.PI]} scale={[-0.76, -0.91, -0.73]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[0, 2.52, 0]} rotation={[-0.6, 0, -Math.PI]} scale={[-0.76, -0.91, -0.73]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[0, 2.88, 0]} rotation={[-0.17, 0, -Math.PI]} scale={[-0.76, -0.91, -0.73]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[0, 0.84, 0]} rotation={[-0.15, 0.08, 2.65]} scale={[-0.76, -0.91, -0.73]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} position={[0, 0.41, 0]} rotation={[-0.15, -0.08, -2.66]} scale={[-0.76, -0.91, -0.73]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={nodes.Cylinder007.material} position={[-0.06, 0.5, -0.03]} rotation={[0.73, -0.08, -2.66]} scale={[-0.58, -0.82, -0.69]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} position={[-0.66, 0.03, -3.39]} rotation={[0.2, 0.12, -1.47]} scale={0.06} />
      <mesh geometry={nodes.Icosphere002.geometry} material={nodes.Icosphere002.material} position={[-0.22, -0.02, 3.82]} rotation={[0.17, 0.26, -0.12]} scale={[0.26, 0.22, 0.24]} />
      <mesh geometry={nodes.Icosphere004.geometry} material={nodes.Icosphere004.material} position={[0.26, -0.02, 3.08]} rotation={[0, 0.79, -0.25]} scale={[0.27, 0.33, 0.26]} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[-0.46, 2.21, -0.84]} rotation={[0, 0, -1.1]} scale={[1, 1, 0.59]} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[-0.23, 4.08, 0.1]} rotation={[-0.37, 0.6, -1.13]} scale={[1.02, 1.07, 0.61]} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[0.55, 2.39, -0.05]} rotation={[0.63, 0.52, -1.44]} scale={[1.08, 1.02, 0.64]} />
      <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[-0.46, 2.39, -0.41]} rotation={[-1.13, 0.45, -1.1]} scale={[1.74, 1.37, 1.02]} />
      <mesh geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} position={[-0.46, 2.39, 0.15]} rotation={[0, -0.74, -1.1]} scale={[1, 1, 0.59]} />
      <mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[-0.46, 3.4, -0.62]} rotation={[0, 0, -1.65]} scale={[1, 1, 0.59]} />
      <mesh geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} position={[-0.46, 2.39, 0.47]} rotation={[0, 0, -1.66]} scale={[1, 0.9, 0.59]} />
      <mesh geometry={nodes.Plane007.geometry} material={nodes.Plane007.material} position={[-0.46, 4.55, -1.13]} rotation={[-Math.PI, -1.41, 2.04]} scale={[1, 1, 0.59]} />
      <mesh geometry={nodes.Plane008.geometry} material={nodes.Plane008.material} position={[-0.46, 2.39, 0.61]} rotation={[0.66, 0, -1.1]} scale={[1.15, 1.04, 0.66]} />
      <mesh geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} position={[0.27, 1.84, 0.41]} rotation={[-0.59, 0.43, -0.71]} scale={[1.2, 1.09, 0.65]} />
      <mesh geometry={nodes.Plane010.geometry} material={nodes.Plane010.material} position={[-0.46, 3.5, 0.24]} rotation={[0, 0, -1.1]} scale={[1.34, 1.1, 0.59]} />
      <mesh geometry={nodes.Plane011.geometry} material={nodes.Plane011.material} position={[0.08, 2.78, 0.93]} rotation={[0, 0, 0.56]} scale={[1.45, 1.95, 0.59]} />
      <mesh geometry={nodes.Plane012.geometry} material={nodes.Plane012.material} position={[-0.46, 3.12, 0.21]} rotation={[-0.16, 0.04, -0.81]} scale={[1.21, 1.23, 0.59]} />
      <mesh geometry={nodes.Plane013.geometry} material={nodes.Plane013.material} position={[0.05, 4.66, 0.43]} rotation={[-0.57, 1.28, -0.26]} scale={[1.68, 1.71, 0.8]} />
      <mesh geometry={nodes.Plane014.geometry} material={nodes.Plane014.material} position={[0.59, 2.96, -0.45]} rotation={[-1.92, 1, 0.99]} scale={[1.68, 1.51, 0.9]} />
      <mesh geometry={nodes.Plane015.geometry} material={nodes.Plane015.material} position={[0.57, 3.7, 0.59]} rotation={[1.22, 0.86, -2.22]} scale={[1.6, 1.43, 0.91]} />
      <mesh geometry={nodes.Plane016.geometry} material={nodes.Plane016.material} position={[-1.02, 5.04, 0.11]} rotation={[0, 1.28, -1.65]} scale={[1.33, 1.35, 0.79]} />
      <mesh geometry={nodes.Plane017.geometry} material={nodes.Plane017.material} position={[0.1, 3.7, -0.99]} rotation={[2.06, 0.95, 3.03]} scale={[1.5, 1.4, 0.89]} />
      <mesh geometry={nodes.Plane018.geometry} material={nodes.Plane018.material} position={[-1.31, 3.45, 0.03]} rotation={[0, 1.28, -1.1]} scale={[1.37, 1.38, 0.79]} />
      <mesh geometry={nodes.Plane019.geometry} material={nodes.Plane019.material} position={[0.56, 5.06, 0.38]} rotation={[1.35, 0.79, -2.67]} scale={[3.07, 2.65, 1.76]} />
      <mesh geometry={nodes.Plane020.geometry} material={nodes.Plane020.material} position={[-0.47, 4.3, 0.47]} rotation={[-0.34, 0.35, -0.89]} scale={[2.31, 2.35, 0.95]} />
      <mesh geometry={nodes.Plane021.geometry} material={nodes.Plane021.material} position={[-0.38, 4.93, 0.38]} rotation={[-0.18, 0.29, -1.22]} scale={[2.47, 2.01, 0.93]} />
      <mesh geometry={nodes.Plane022.geometry} material={nodes.Plane022.material} position={[-0.78, 4.54, -0.87]} rotation={[-0.18, 0.29, -1.77]} scale={[1.69, 1.68, 0.93]} />
      <mesh geometry={nodes.Plane023.geometry} material={nodes.Plane023.material} position={[-1.12, 2.53, -0.77]} rotation={[-0.18, 0.29, -1.22]} scale={[1.84, 1.83, 0.93]} />
    </group>
  )
}

useGLTF.preload('/sample-island.glb')
